Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network :forwarded_port, guest: 9000, host: 9090
    config.vm.network :forwarded_port, guest: 8000, host: 8080
    config.vm.provision :shell, path: "vagrant.sh"
end